points:
- x: -13.29124417541343
  y: -25.215388949927192
- x: -12.759594408396893
  y: 20.658390946928304
- x: -40.97659060043774
  y: 13.454999898651199
- x: -47.58177236886651
  y: 3.669545426904872
- x: -47.948726911556996
  y: -23.240454370397526
- x: -33.75981792752482
  y: -30.090272500619953
- x: 3.424909065111214
  y: -22.139590742326064
- x: 10.030090833539985
  y: -3.791863607801701
- x: 7.094454492016086
  y: 15.167454431206805
