robots:
- frame_id: vicon
  orientation:
    w: 0.9999887085548466
    x: 0.0029373520332450437
    y: -0.0002942504214025949
    z: 0.003723995506525181
  position:
    x: -35.325144711312525
    y: 2.0745059942337347
    z: 211.5599707816407
  timestamp: '2025-06-03T21:10:24Z'
  vicon_topic: /vicon/limo_01/limo_01
